services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      args:
        BUNDLE_WITHOUT: ""
    command: sh -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      RAILS_ENV: development
      BUNDLE_WITHOUT: ""
    depends_on:
      - db

  tester:
    build: .
    profiles: ["test"]
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres:password@db:5432/cgt_test_be_test
    depends_on:
      - db
